trigger:
- main

pool:
  name: Default

variables:
  # python.version: '3.7.6'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'Temp-connection1'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: 'test'

stages:
- stage: Build
  jobs:
  - job: clean
    displayName: Clean dir
    workspace:
      clean: all
  
  - job: BuildInfrastructure
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Terrafom installation'
      inputs:
        terraformVersion: '1.2.9'

    - task: TerraformTaskV3@3
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: 'Temp connection 3'
        backendAzureRmResourceGroupName: 'Azuredevops'
        backendAzureRmStorageAccountName: 'tfstate603110144'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'test.terraform.tfstate'

    - task: TerraformTaskV3@3
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'

    - task: DownloadSecureFile@1
      displayName: Download SSH public key
      inputs:
        secureFile: 'azure_rsa.pub'

    - task: TerraformTaskV3@3
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: 'Temp connection 3'

    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)/automatedtesting/postman
        
    - task: CmdLine@2
      displayName: Run Data Validation Tests
      continueOnError: true
      # 'newman run TestSuite.Data-Validation.json -e Test.environment.json --reporters cli,junit --reporter-junit-export TEST-DataValidation.xml'
      inputs:
        script: 'newman run StarterAPIs.json --reporters cli,junit --reporter-junit-export TEST-DataValidation.xml'
        workingDirectory: $(System.DefaultWorkingDirectory)/automatedtesting/postman

    - task: CmdLine@2
      displayName: 60 Secs sleep
      inputs:
        script: |
          echo sleeping for 30 seconds
          sleep 60 && echo Dummy API has some throttling

    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      # 'newman run TestSuite.Regression.json -e Test.environment.json --reporters cli,junit --reporter-junit-export TEST-Regression.xml'
      inputs:
        script: 'newman run TestSuite.Regression.json --reporters cli,junit --reporter-junit-export TEST-Regression.xml'
        workingDirectory: $(System.DefaultWorkingDirectory)/automatedtesting/postman

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        mergeTestResults: true

    - task: ArchiveFiles@2
      displayName: 'Archive UI Tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip   # Same as the archiveFile artifact above. 
      displayName: 'Upload Package'
      artifact: drop-uitests

    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi

    - task: ArchiveFiles@2
      displayName: 'Archive PerformanceTestSuite'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-perftests.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-perftests.zip
      displayName: 'Upload Package'
      artifact: drop-perftests

- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool:
      name: Default
    environment: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'Temp connection 3'
              appType: 'webApp'
              appName: 'sampleApplication-AppService'
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
              deploymentMethod: 'auto'
          - task: CmdLine@2
            displayName: Jmeter test
            inputs:
              script: |
                unzip -o $(Build.BuildId)-perftests.zip
                ~/Dev/Projects/Project-DevOps/apache-jmeter-5.6/bin/jmeter -n -t Starter.jmx -j jmeter.log
                cat jmeter.log                                                   
              workingDirectory: '$(Pipeline.Workspace)/drop-perftests'

  - deployment: VMDeploy
    dependsOn: FakeRestAPI
    displayName: Selenium Tests
    environment:
      name: Default
      # resourceType: VirtualMachine
      # tags: selenium
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop-uitests
            
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                
                sudo apt-get update -y
                sudo apt-get upgrade -y
                cd ~/
                DIR=/home/azureUser/app
                if [ ! -d "$DIR" ]; then
                    mkdir app
                fi
                mv /home/root-admin/Downloads/myagent/~/Dev/11/drop-uitests/$(Build.BuildId)-uitests.zip app
                cd app
                unzip -o $(Build.BuildId)-uitests.zip
                export PATH=$PATH:/home/azureUser/app
                pip install selenium
                echo "Starting Selenium Tests"
                python3 login.py >> selenium.log
                echo "Completed Selenium Tests. Check selenium.log for results."